# Generated by Django 5.1.1 on 2024-09-05 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_list',
            field=models.ManyToManyField(blank=True, related_name='blocked_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
