# Generated by Django 5.1 on 2024-09-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_update_on',
            field=models.IntegerField(default=0),
        ),
    ]
