# Generated by Django 5.1 on 2024-09-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.JSONField()),
                ('red_team', models.JSONField()),
                ('blue_team', models.JSONField()),
                ('red_team_score', models.IntegerField(default=0)),
                ('blue_team_score', models.IntegerField(default=0)),
                ('host', models.CharField(max_length=20)),
                ('room_name', models.CharField(max_length=20)),
                ('team_size', models.IntegerField(default=1)),
                ('gamemode', models.CharField(max_length=20)),
                ('time', models.IntegerField(default=3)),
                ('customization', models.CharField(blank=True, default=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='match',
            field=models.ManyToManyField(blank=True, to='api.room'),
        ),
    ]
