# Generated by Django 5.1 on 2024-08-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
