# Generated by Django 5.0.7 on 2024-07-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_pfp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
