# Generated by Django 5.0.7 on 2024-07-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
