# Generated by Django 5.1 on 2024-08-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_can_update_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_update_on',
            field=models.IntegerField(default=1725027946),
        ),
    ]
