# Generated by Django 5.0.7 on 2024-07-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profile_pictures/'),
        ),
    ]
