# Generated by Django 5.0.7 on 2024-07-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_update_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='count_updates',
            field=models.IntegerField(default=5),
        ),
    ]
