# Generated by Django 5.0.7 on 2024-07-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_can_update_on_user_count_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count_updates',
            field=models.IntegerField(default=2),
        ),
    ]
