# Generated by Django 5.1 on 2024-08-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_user_can_update_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_update_on',
            field=models.IntegerField(default=1724936161),
        ),
    ]
