# Generated by Django 5.1 on 2024-08-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_user_can_update_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_update_on',
            field=models.IntegerField(default=1724573365),
        ),
    ]
